name: Production-Release

on: workflow_dispatch

env:
 EXCLUDE_ENTERPRISE: true
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: "focalboard"

    - name: npm ci
      run: cd focalboard/webapp; npm ci --no-optional

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0

    - name: apt-get update
      run: sudo apt-get update

    - name: apt-get install -y libgtk-3-dev
      run: sudo apt-get install -y libgtk-3-dev

    - name: apt-get install -y libwebkit2gtk-4.0-dev
      run: sudo apt-get install -y libwebkit2gtk-4.0-dev

    - name: Build Linux server and app
      run: cd focalboard; make server-linux-package linux-app
      env:
        BUILD_NUMBER: ${{ github.run_id }}

    - name: Upload server package
      uses: actions/upload-artifact@v3
      with:
        name: focalboard-server-linux-amd64.tar.gz
        path: ${{ github.workspace }}/focalboard/dist/focalboard-server-linux-amd64.tar.gz

    - name: Upload app package
      uses: actions/upload-artifact@v3
      with:
        name: focalboard-linux.tar.gz
        path: ${{ github.workspace }}/focalboard/linux/dist/focalboard-linux.tar.gz  
